"""Alter User

Revision ID: 677397def9ef
Revises: 2457a5be450b
Create Date: 2024-11-19 14:12:02.789049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '677397def9ef'
down_revision: Union[str, None] = '2457a5be450b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('participate',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('settime', sa.DateTime(), nullable=False),
    sa.Column('fortime', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('user', 'ptime')
    op.drop_column('user', 'p')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('p', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('ptime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_table('participate')
    # ### end Alembic commands ###
